[package]
name = "Examples"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../framework/aptos-framework" }
AptosToken = { local = "../framework/aptos-token" }

[addresses]
aptos_framework = "0x1"
# change it to the actual source address when publishing the module
source_addr = "0xcafe"
# change it to the actual admin address when publishing the module
admin_addr = "0xad"